---
title: "Impact Analysis 2018-2019"
author: "Andrew M. Demetriou"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
          toc: true
---

```{r setup, include=FALSE}
library('knitr')        # report generation

library('here')         # file logistics
library('haven')        # importing SPSS .sav files
library('labelled')     # working with SPSS labels

library('dplyr')        # code logistics
library('tidyr')        # pivoting
library('purrr')        # multiple left joins

library('ggplot2')      # general visualization
#library('ggdist')       # raincloud plotting
#library('gghalves')     # raincloud plotting
#library('corrplot')     # visualizing correlations
#library('forcats')      # reorder bars

library('naniar')       # missingness

library('psych')        # reliability analysis

library('lavaan')       # SEM
library('lavaanPlot')   # visualizing results

#library('lme4')         # multilevel modelling
#library('lmerTest')     # add statistical tests
#library('performance')  # checking assumptions
#library('broom.mixed')  # tibbles from model output


knitr::opts_chunk$set(include = FALSE, echo=FALSE)

#color scheme
ciri_colors <- c('#fe7241', '#ae5944', '#543c4a', '#67444a')
```

```{r import_data}
#SPSS data file path
data_file_path <- here("data_", "2018_2019_")

#create a list of all files
data_files     <- list.files(here("data_", "2018_2019_"))

#read in SPSS files
T0_df <- read_sav(paste0(data_file_path, "/", data_files[3]))
T1_df <- read_sav(paste0(data_file_path, "/", data_files[4]))
T2_df <- read_sav(paste0(data_file_path, "/", data_files[5]))

rm(data_file_path, data_files)
```

### Constructs

```{r constructs_df}
##Participant ID:
Accountnummer <- 'Accountnummer'

##Entrepreneurial Intentions:
intentions_vars <- c(paste0("Intention_000", seq(1,9)))

##Entrepreneurial Skills 
Entrskills_vars <- c("Entrskills_0001", "Entrskills_0002", "Entrskills_0003", "Entrskills_0004", "Entrskills_0005", "Entrskills_0006", "Entrskills_0007")

##Personal Skills:
perskills_vars <- c(paste0("Perskills_000", seq(01,09)), paste0("Perskills_00", seq(10,15)))

##Need for Achievement
NFA_vars <- c("NfA_0001","NfA_0002","NfA_0003","NfA_0004")

##Locus of Control
LoC_vars <- c('LoC_0001','LoC_0002','LoC_0003','LoC_0004','LoC_0005','LoC_0006')

#LoC subscales
LoC_internal_vars <- c('LoC_0001','LoC_0002','LoC_0003')
LoC_external_vars <- c('LoC_0004','LoC_0005','LoC_0006')

##Tolerance for Ambiguity
TfA_vars <- c('TfA_0001','TfA_0002','TfA_0003','TfA_0004')

constructs <- list(Entrskills_vars, perskills_vars, NFA_vars, LoC_vars, LoC_internal_vars, LoC_external_vars, TfA_vars)
names(constructs) <- c("Entrskills_vars", "perskills_vars", "NFA_vars", "LoC_vars", "LoC_internal_vars", "LoC_external_vars", "TfA_vars")

#assemble df
#T0_constructs_df <- T0_df[c(Accountnummer, intentions_vars, Entrskills_vars, perskills_vars, NFA_vars, LoC_vars, LoC_internal_vars, LoC_external_vars, TfA_vars)]

T0_constructs_df <- T0_df[c(Accountnummer, intentions_vars, Entrskills_vars, perskills_vars, NFA_vars, LoC_vars,TfA_vars)]

#T1_constructs_df <- T1_df[c(Accountnummer, intentions_vars, Entrskills_vars, perskills_vars, NFA_vars, LoC_vars, LoC_internal_vars, LoC_external_vars, TfA_vars)]

T1_constructs_df <- T1_df[c(Accountnummer, intentions_vars, Entrskills_vars, perskills_vars, NFA_vars, LoC_vars, TfA_vars)]

#T2_constructs_df <- T2_df[c(Accountnummer, intentions_vars, Entrskills_vars, perskills_vars, NFA_vars, LoC_vars, LoC_internal_vars, LoC_external_vars, TfA_vars)]

T2_constructs_df <- T2_df[c(Accountnummer, intentions_vars, Entrskills_vars, perskills_vars, NFA_vars, LoC_vars, TfA_vars)]


#perskills all appear to be phrased in the positive
#var_label(T0_df[constructs$perskills_vars])

#tfa 3 and 4 should be reverse scored
#var_label((T0_df[constructs$TfA_vars]))

#Tolerance for Ambiguity reverse scoring
T0_constructs_df$TfA_0003 <- T0_constructs_df$TfA_0003 * -1
T1_constructs_df$TfA_0003 <- T1_constructs_df$TfA_0003 * -1
T2_constructs_df$TfA_0003 <- T2_constructs_df$TfA_0003 * -1

T0_constructs_df$TfA_0004 <- T0_constructs_df$TfA_0004 * -1
T1_constructs_df$TfA_0004 <- T1_constructs_df$TfA_0004 * -1
T2_constructs_df$TfA_0004 <- T2_constructs_df$TfA_0004 * -1

#Locus of Control Reverse Scoring
T0_constructs_df$LoC_0004 <- T0_constructs_df$LoC_0004 * -1
T0_constructs_df$LoC_0006 <- T0_constructs_df$LoC_0006 * -1

T1_constructs_df$LoC_0004 <- T1_constructs_df$LoC_0004 * -1
T1_constructs_df$LoC_0006 <- T1_constructs_df$LoC_0006 * -1

T2_constructs_df$LoC_0004 <- T2_constructs_df$LoC_0004 * -1
T2_constructs_df$LoC_0006 <- T2_constructs_df$LoC_0006 * -1


rm(Accountnummer, Entrskills_vars, intentions_vars, LoC_vars, NFA_vars, LoC_internal_vars, LoC_external_vars, perskills_vars, TfA_vars, T0_df, T1_df, T2_df)
```

```{r get_alpha_function}
get_alpha_ci <- function(df){
  alpha <- psych::alpha(df, n.iter=500)
  return(alpha$boot.ci)
}
```

```{r assemble_alpha_df_function}
assemble_alpha_df <- function(df, vars) {
  
  ## make an identifier for the specific construct
  
  # get the name of the dataframe
  df_name <- deparse(substitute(df)) %>%
    # should return time point of measure e.g. 'T0'
    scan(text = ., comment.char='_', what="")
  
  # get name of construct
  vars_name <- deparse(substitute(vars)) %>%
      #should return construct name e.g. 'LoC'
      scan(text = ., comment.char='_', what="")
  
  # put the two together
  name <- paste0(df_name, "_", vars_name)
  
  ## make a dataframe for results
  
  # get relevant columns from df
  results <- df[vars] %>%
    # compute alpha on the set
    get_alpha_ci() %>%
    # convert to df
    as.data.frame()
  
  # make the rownames a column
  results <- tibble::rownames_to_column(results)
  
  # rename columns
  colnames(results) <- c("Interval", name)
  
  # tell R what to return
  return(results)
}

#s <- assemble_alpha_df(T0_constructs_df, Entrskills_vars)
#t <- assemble_alpha_df(T0_constructs_df, perskills_vars)
```


```{r alpha_summary_df}
alpha_summary_df_T0 <- lapply(constructs, assemble_alpha_df, df=T0_constructs_df) %>%
  lapply(., pivot_wider, names_from = Interval, values_from = `T0_X[[i]]`) %>%
  bind_rows(., .id='Construct')

alpha_summary_df_T1 <- lapply(constructs, assemble_alpha_df, df=T1_constructs_df) %>%
  lapply(., pivot_wider, names_from = Interval, values_from = `T1_X[[i]]`) %>%
  bind_rows(., .id='Construct')

alpha_summary_df_T2 <- lapply(constructs, assemble_alpha_df, df=T2_constructs_df) %>%
  lapply(., pivot_wider, names_from = Interval, values_from = `T2_X[[i]]`) %>%
  bind_rows(., .id='Construct')
```

```{r alpha_plot}
alpha_summary_df_T0 %>% ggplot(., aes(x=Construct, y=`50%`)) +
  geom_point() +
  geom_errorbar(aes(ymin=`2.5%`, ymax=`97.5%`, color=Construct)) +
  theme_minimal()

alpha_summary_df_T1 %>% ggplot(., aes(x=Construct, y=`50%`)) +
  geom_point() +
  geom_errorbar(aes(ymin=`2.5%`, ymax=`97.5%`, color=Construct)) +
  theme_minimal()

alpha_summary_df_T2 %>% ggplot(., aes(x=Construct, y=`50%`)) +
  geom_point() +
  geom_errorbar(aes(ymin=`2.5%`, ymax=`97.5%`, color=Construct)) +
  theme_minimal()

rm(alpha_summary_df_T0, alpha_summary_df_T1, alpha_summary_df_T2)
```

```{r factor_analysis}
#MR* are the factors reflecting the fitting method
#h* is the amount of variance in variable explained by factors (commonality)
#u* is residual variance (uniqueness)

#running the object gives you the proportion of variance explained by the factor
fa_LoC_2 <- psych::fa(T0_constructs_df[constructs$LoC_vars], 2)
fa_LoC_2

fa_LoC_1 <- psych::fa(T0_constructs_df[constructs$LoC_vars], 1)
fa_LoC_1

fa_Tfa <- psych::fa(T0_constructs_df[constructs$TfA_vars])
fa_Tfa

rm(fa_LoC_1, fa_LoC_2, fa_Tfa)
```
### Analyze Missingness in Income Reporting

```{r missingness_table, include=TRUE}
missingness_table_T0 <- T0_constructs_df %>%
  select(-Accountnummer) %>%
  miss_var_summary(order=FALSE)

colnames(missingness_table_T0) <- c("Time", "Number Missing", "Percent Missing")

missingness_table_T1 <- T1_constructs_df %>%
  select(-Accountnummer) %>%
  miss_var_summary(order=FALSE)

colnames(missingness_table_T1) <- c("Time", "Number Missing", "Percent Missing")


missingness_table_T2 <- T2_constructs_df %>%
  select(-Accountnummer) %>%
  miss_var_summary(order=FALSE)

colnames(missingness_table_T2) <- c("Time", "Number Missing", "Percent Missing")

missingness_table_T0
missingness_table_T1
missingness_table_T2

rm(missingness_table_T0, missingness_table_T1, missingness_table_T2)
```

```{r intersection_plot, include=TRUE,fig.cap="Figure 3.1: Missingness per combination of time points."}
#merge(T1_constructs_df, T2_constructs_df, by="Accountnummer") %>%
#  gg_miss_upset()

T1_constructs_df %>%
  gg_miss_upset()
```

#need for achievement
```{r}
NFA_model <- ' NFA =~ NfA_0001 + NfA_0002 + NfA_0003 + NfA_0004'

NFA_fit   <- cfa(NFA_model,data=T0_constructs_df, std.lv=TRUE)

lavaanPlot(model=NFA_fit, node_options = list(fontname = "Helvetica"), edge_options = list(color = "grey"),coefs=TRUE, stars='latent')

summary(NFA_fit)
```

#Locus of Control
```{r}
LoC_model <- ' LoC_internal =~ LoC_0001 + LoC_0002 + LoC_0003 
               LoC_external =~ LoC_0004 + LoC_0005 + LoC_0006
               LoC_internal ~~ LoC_external '

LoC_fit   <- cfa(LoC_model,data=T0_constructs_df, std.lv=TRUE)
lavaanPlot(model=LoC_fit, node_options = list(fontname = "Helvetica"), edge_options = list(color = "grey"), coefs=TRUE, covs=TRUE, stars='latent')
summary(LoC_fit)
```

```{r}
big_bad_model <- 
  ' NFA =~ NfA_0001 + NfA_0002 + NfA_0003 + NfA_0004
    LoC_internal =~ LoC_0001 + LoC_0002 + LoC_0003 
    Entrskills =~ Entrskills_0001 + Entrskills_0002 +Entrskills_0003 + Entrskills_0004 + Entrskills_0005 + Entrskills_0006 + Entrskills_0007
    LoC_internal ~~ NFA
    LoC_internal ~~ Entrskills
    NFA ~~ Entrskills
'

big_bad_fit <- cfa(big_bad_model,data=T0_constructs_df, std.lv=TRUE)
lavaanPlot(model=big_bad_fit, node_options = list(fontname = "Helvetica"), edge_options = list(color = "grey"), coefs=TRUE, covs=TRUE, stars='latent')

```


