---
title: "initial_study"
author: "Andrew M. Demetriou"
date: "10/1/2021"
---

```{r}
library('here')         #file logistics
library('dplyr')        #code logistics
library('haven')        #for importing SPSS files
library('lavaan')       #for SEM analyses
library('lavaanPlot')   #visualizing results
library('psych')        #internal reliability
```

```{r}
data_file_path <- here("data_", "2018_2019_")
data_files <- list.files(here("data_", "2018_2019_"))
df_1 <- read_sav(paste0(data_file_path, "/", data_files[2])) #2018_2019 data set
```

#internal reliabilities
```{r}
NFA_alpha <- df_1 %>% select(NfA_0001,NfA_0002,NfA_0003,NfA_0004) %>% alpha(., n.iter=5000)

LoC_alpha <- df_1 %>% select(LoC_0001,LoC_0002,LoC_0003,LoC_0004,LoC_0005,LoC_0006) %>% alpha(., check.keys=TRUE, n.iter=5000)
#LoC_internal_alpha <- df_1 %>% select(LoC_0001,LoC_0002,LoC_0003) %>% alpha(., check.keys=TRUE, n.iter=5000)
#LoC_external_alpha <- df_1 %>% select(LoC_0004,LoC_0005,LoC_0006) %>% alpha(., check.keys=TRUE, n.iter=5000)

ToA_alpha <- df_1 %>% select(TfA_0001,TfA_0002,TfA_0003,TfA_0004) %>% alpha(., check.keys=TRUE, n.iter = 5000)

constructs <- list(NFA_alpha, LoC_alpha, ToA_alpha)
construct_names <- c('NFA', 'LoC', 'ToA')
```

```{r}
get_alpha_ci <- function(alpha_df){
  lower <- alpha_df$total$raw_alpha - 1.96 * alpha_df$total$ase
  estimate <- alpha_df$total$raw_alpha
  upper <- alpha_df$total$raw_alpha + 1.96 * alpha_df$total$ase

results <- round(c(lower, estimate, upper), 2)
return(results)
}
```

```{r}
alphas <- setNames(data.frame(matrix(ncol=4, nrow=0)), c('construct', 'lower', 'estimate', 'upper'))


for(i in 1:length(constructs)) {
  alphas[i,1] <- construct_names[i]
  alpha_ci <- get_alpha_ci(constructs[[i]])
  alphas[i,2] <- alpha_ci[1]
  alphas[i,3] <- alpha_ci[2]
  alphas[i,4] <- alpha_ci[3]
}
```

```{r}
#NFA_fa <- df_1 %>% select(NfA_0001,NfA_0002,NfA_0003,NfA_0004) %>% fa()
NFA_fa <- df_1 %>% select(NfA_0001,NfA_0002,NfA_0003,NfA_0004) %>% fa(., rotate='varimax')
LoC_fa <- df_1 %>% select(NfA_0001,NfA_0002,NfA_0003,NfA_0004) %>% fa(., rotate='varimax')
```


#need for achievement
```{r}
NFA_model <- ' NFA =~ NfA_0001 + NfA_0002 + NfA_0003 + NfA_0004'
NFA_fit   <- cfa(NFA_model,data=df_1, std.lv=TRUE)
lavaanPlot(model=NFA_fit, node_options = list(fontname = "Helvetica"), edge_options = list(color = "grey"),coefs=TRUE, stars='latent')
#summary(NFA_fit)
```

#Locus of Control
```{r}
LoC_model <- ' LoC_internal =~ LoC_0001 + LoC_0002 + LoC_0003 
               LoC_external =~ LoC_0004 + LoC_0005 + LoC_0006
               LoC_internal ~~ LoC_external '

LoC_fit   <- cfa(LoC_model,data=df_1)
lavaanPlot(model=LoC_fit, node_options = list(fontname = "Helvetica"), edge_options = list(color = "grey"),coefs=TRUE)
summary(LoC_fit)
```

```{r}
TfA_model <- ' TfA =~ TfA_0001 + TfA_0002 + TfA_0003 + TfA_0004 '
```

```{r}
LoC <- df_1 %>% select(LoC_0001,LoC_0002,LoC_0003,LoC_0004,LoC_0005,LoC_0006) %>% mutate(mean_LoC = LoC_0001 + LoC_0002 + LoC_0003 + LoC_0004 + LoC_0005 + LoC_0006 / 6)

hist(LoC$mean_LoC)
```

