---
title: "typeform 'why'"
author: "Andrew M. Demetriou"
---

```{r setup, include = FALSE}
library('knitr')        # report generation

library('here')         # file logistics
library('dplyr')        # code logistics

library('forcats')      # reorder bars
library('ggplot2')      # general visualization

#report options
knitr::opts_chunk$set(echo = FALSE)

#color scheme
ciri_colors <- c('#fe7241', '#ae5944', '#543c4a', '#67444a')
```

```{r file_import, include = FALSE}
#intial measurements; t0
data_file_path <- here("data_")
data_folders   <- list.files(data_file_path)
file_name      <- "responses.csv"

#read in typeform files:

#"Onboarding Form CBL - August 2021"
T0_df <- read.csv(paste0(data_file_path, "/", data_folders[3], "/", file_name))
#"CBL Feedbak Day 1 & 2"
T1_df <- read.csv(paste0(data_file_path, "/", data_folders[2], "/", file_name))

rm(data_file_path, data_folders, file_name)

#identify participants
#participant_ID <- "Email.verification"
```

```{r}
#extract variables
#t <- colnames(T0_df)
#write.csv(as.data.frame(t), "columns.csv")
```


# Why do participants sign up?

```{r why_questions, include = FALSE}
#column names
why_vars <- c(
 "To.improve.my.personal.skills",
 "To.increase.my.income",
 "To.become.a..fulltime..creative.entrepreneur",
 "To.improve.my.entrepreneurial.skills",
 "To.learn.more.about.entrepreneurialism",
 "To.start.a..creative..company",
 "To.learn.how.to.better.manage.my.current.creative.business",
 "To.better.profile.myself.as.an.entrepreneur",
 "To.start.seeing.myself.more.as.an.entrepreneur",
 "Because.I.m.having.difficulty.making.money.from.my.creativity",                   
 "Because.I.lack.business.knowhow",                   
 "Because.the.time.I.spend.on.business.is.hurting.my.creativity",                   
 "Because.I.don.t.have.enough.time.to.develop.a.long.term.strategy",                   
 "Because.I.want.to.put.a.value.on.my.creativity",
 "Other"
 )

#actual wording from questions
why_reasons <- c(
  "To improve my personal skills", 
  "To increase my income", 
  "To become a (fulltime) creative entrepreneur", 
  "To improve my entrepreneurial skills",
  "To learn more about entrepreneurialism",
  "To start a (creative) company",
  "To learn how to better manage my current creative business", 
  "To better profile myself as an entrepreneur",
  "To start seeing myself more as an entrepreneur",
  "Because I'm having difficulty making money from my creativity",
  "Because I lack business knowhow",
  "Because the time I spend on business is hurting my creativity",
  "Because I don't have enough time to develop a long term strategy",
  "Because I want to put a value on my creativity", 
  "Other")

#select columns
why_df   <- T0_df %>% select(why_vars)
colnames(why_df) <- c(paste0("why_000", seq(1,9)), paste0("why_00", seq(10,15)))
```


```{r why_dataframe, inlcude = FALSE}
# number of participants
n_t0 <- nrow(T0_df)

#responses in columns are strings: convert to numeric
why_as_numeric <- data.frame(lapply(why_df[,2:15], function(x) as.numeric(x != "")))

#replace columns in original dataframe
why_df[, 1:15] <- why_as_numeric

#replace NA values with 0
why_df[is.na(why_df)] <- 0
why_df[, 1:15] <- lapply(why_df[, 2:15], factor)

#clear trash
rm(why_as_numeric)
```

```{r why_plot}
#initialize results df
why_results_df <- colnames(why_df) %>% as.data.frame()
colnames(why_results_df) <- "Column_name"

#function to count and re-arrange by frequency of response
extract_freq <- function (...) {
  why_df %>% count(...) %>% arrange(desc(n))
}

#apply custom function to out frequency dataframe
#this creates a list of tibbles with frequency counts
#one for each reason 'why'
freq_df <- apply(X = why_df, MARGIN=2, extract_freq)

#rename the columns of each item in the list
for(i in 1:length(freq_df)) {
  freq_df[[i]]$Column <- names(freq_df[i])
  names(freq_df[[i]]) <- c("Variable", "n", "Column_name")
}

#merge list items into a single df
freq_df <- do.call(rbind, freq_df) %>% 
  #convert to dataframe and reorder columns
  data.frame() %>% select(Column_name,Variable,n)

#only include rows that indicate that the reason was selected
#add a row indicate a percentage based on whether or not the item was selected
freq_df <- freq_df %>% group_by(Column_name) %>% filter(Variable == 1) %>% merge(why_results_df, ., by = 'Column_name', all.x=TRUE) %>% mutate(percent = round(n/n_t0 * 100, digits = 10))
freq_df[is.na(freq_df)] <- 0

#add reasons to datafame translated to English
freq_df$reasons <- why_reasons

#put rows in descending order based on percentage
freq_df$reasons <- factor(freq_df$reasons) %>%
  fct_reorder(freq_df$percent)

#plot results
freq_df %>%
  ggplot(aes(x=reasons, y=percent)) +
  geom_col(fill=ciri_colors[2]) +
  coord_flip() +
  scale_x_discrete("",position = "top") +
  scale_y_continuous("Percentage") +
  theme_minimal()

most_selected_reason <- freq_df %>% filter(percent == max(freq_df$percent))

rm(why_df, why_results_df, freq_df, i, n_t0, why_reasons, why_vars, reasons, reason, extract_freq)
```

## Which module to participants think is the most important?


```{r belang}
modules <- c(
  "Module 1 - Identiteit & Kracht", 
  "Module 2 - Doelgroep & Waarde", 
  "Module 3 - Visie & Strategie", 
  "Module 4 - Intellectueel Eigendomsrecht", 
  "Module 5 - Financiële & Fiscale kennis", 
  "Module 6 - Sales & Marketing", 
  "Module 7 - Organisatie & Processen")

#select column
belang_df <- factor(T0_df$Which.component.of.this.program.do.you.consider.most.valuable.to.you.at.this.point.)

#convert to frequency table
belang_df <- data.frame(table(belang_df))
belang_df$time <- "T0"
colnames(belang_df) <- c("module", "frequency", "time")

#belang_t2 <- factor(T2_df$Belang_module, val_labels(T2_df$Belang_module))
#belang_t2 <- data.frame(table(belang_t2))
#belang_t2$module <- names(val_labels(T2_df$Belang_module))
#belang_t2$time <- "T2"
#colnames(belang_t2) <- c("belang_df", "frequency", "module", "time")

#belang_df <- rbind(belang_df, belang_t2)

belang_df %>%
  ggplot(aes(x=frequency, y=module, fill=time)) +
  geom_col(stat="identity", position = "dodge")
```

```{r reason_table}
reason    <- "Can.you.explain.why.you.chose....field.a3329bb5.67ab.418c.a388.237285d8ecda....."
reasons <- T0_df[reason]
#kable(reasons, col.names = "Reasons", align = "l", caption="")
```




