---
title: "descriptives and income"
author: "Andrew M. Demetriou"
date: "6/17/2022"
output: html_document
---

```{r why_setup, include=FALSE}
library('here')      # file logistics
library('tidyverse') # code logistics
library('xlsx')      # excel export
```

```{r import_data}
#define data folder
data_folder <- here("data_")

#names of subfolders
sub_folders <- c("WerktuigPPO |  FebMar", "WerktuigPPO |  May", "WerktuigPPO |  June")

#make list of dataframes for all subfolders
list_of_data_frames <- lapply(sub_folders, function(x){
  read.csv(here(data_folder, x, 'responses.csv'))
})

#name subfolders
names(list_of_data_frames) <- sub_folders

#bind into a single dataframe
T0_df <- bind_rows(list_of_data_frames, .id = ".id")

#questions <- colnames(T0_df) %>% as.data.frame()

rm(data_folder, sub_folders, list_of_data_frames)
```

```{r}
#remove identifiers
id_vars <- c("Even.voorstellen..Wat.is.jouw.voornaam.", "En.dan.natuurlijk..wat.is.jouw.achternaam.", "Wat.is.jouw.KvK.nummer.")

export_df <- T0_df |> select(-id_vars)

#dataset export for PAACT
#csv
#path <- here("PPO", "intermediary_data", "PPO_T0.csv")
#write_csv(export_df, file = path)

#xlsx
#path <- here("PPO", "intermediary_data", "PPO_T0.xlsx")
#write.xlsx(export_df, file = path)

#rm(export_df)
```

```{r}
#make list of dataframes for all subfolders
data_folder = "data_/PPO_raw"

files <- list.files(here(data_folder))

list_of_data_frames <- lapply(files, function(x){
  read.xlsx(here(data_folder, x), sheetIndex=1)[1:3]
})

# add column of dataset names
names(list_of_data_frames) <- files
#bind dataframes together
ppo_names_df <- bind_rows(list_of_data_frames, .id = ".id")


ppo_names_df$Achternaam <- tolower(ppo_names_df$Achternaam)
ppo_names_df$Voornaam <- tolower(ppo_names_df$Voornaam)

rm(list_of_data_frames, files, data_folder)
```

```{r}
# identifying info
id_vars <- c(".id", "X.", "Even.voorstellen..Wat.is.jouw.voornaam.", "En.dan.natuurlijk..wat.is.jouw.achternaam.")

# total names in ciri data
ciri_names_df <- T0_df[id_vars]
colnames(ciri_names_df) <- c(".id", "X.", "Voornaam", "Achternaam")

ciri_names_df$Achternaam <- tolower(ciri_names_df$Achternaam)
ciri_names_df$Voornaam <- tolower(ciri_names_df$Voornaam)

ciri_names_df <- ciri_names_df |> select(-X.)

#n_occur <- data.frame(table(ciri_names_df$X.)) |> arrange(desc(Freq))
#path <- here("PPO", "intermediary_data", "ciri_names.xlsx")
#write.xlsx(ciri_names_df, file = path)
```

```{r}
# remove incomplete rows
ciri_names_df$Voornaam[ciri_names_df$Voornaam==""] <- NA
ciri_names_df$Achternaam[ciri_names_df$Achternaam==""] <- NA

ciri_names_df <-ciri_names_df |> filter(complete.cases(Achternaam)) |>
  filter(! Voornaam == "k")
```


```{r}
# merged on all names: note, there are duplicates in the PPO records
merged_names_df <- merge(ciri_names_df, ppo_names_df, by.x = c("Achternaam", "Voornaam"), by.y=c("Achternaam","Voornaam"), all.x = TRUE) 

# 6 duplicates
doubles_df <- data.frame(table(merged_names_df$Achternaam, merged_names_df$Voornaam)) |> arrange(desc(Freq)) |> filter(Freq > 1)
```

```{r}
matched_names_df <- merged_names_df |>
  filter(complete.cases(Nr.))
```

```{r}
missing_names_df <- merged_names_df |> 
  filter(! complete.cases(Nr.)) 

missing_names_df$Voornaam[missing_names_df$Voornaam==""] <- NA
missing_names_df$Achternaam[missing_names_df$Achternaam==""] <- NA

missing_names_df <- missing_names_df |>
  filter(complete.cases(Achternaam, Voornaam))
```

```{r}
# double entry in merged names df

#doubles <- data.frame(table(merged_names_df$X.)) |> filter(Freq > 1) 
#colnames(doubles) <- c("X.", "Freq")
#doubles_df <- merge(doubles, merged_names_df, by = "X.")
#path <- here("PPO", "intermediary_data", "doubles.xlsx")
#write.xlsx(doubles_df, file = path)
```


```{r}
achternaam_matched_names_df <-merge(missing_names_df, ppo_names_df, by = "Achternaam", all.x = T) |>
  select(Voornaam.x, Voornaam.y, Achternaam, .id.x, Nr..y)

colnames(achternaam_matched_names_df) <- c("Voornaam.ciri", "Voornaam.PPO", "Achternaam.ciri", ".id.x", "Nr.")

# manually adding:
# Dataset maart 2022 tbv CIRI.xlsx 23929 nunes van den hoven anna
achternaam_matched_names_df[achternaam_matched_names_df$Voornaam.ciri=="anna", "Nr."] <- 23929

# manually adding:
# Dataset april 2022 tbv CIRI.xlsx 24191 de groot tamara
achternaam_matched_names_df[achternaam_matched_names_df$Voornaam.ciri=="tamara", "Nr."] <- 24191

#path <- here("PPO", "intermediary_data", "missing_names.xlsx")
#write.xlsx(missing_names_df, file = path)
```