---
title: "IRT"
author: "Andrew M. Demetriou"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
          toc: true
---

```{r setup, include=FALSE}
library('here')         # file logistics

library('tidyverse')    # code logistics

library('ggplot2')      # general visualization
library('cowplot')      # multiple plots

library('mirt')         # irt analysis

# custom script to format dataframes
source((here("PPO", "PPO_constructs_formatting.R")))

knitr::opts_chunk$set(include = FALSE, echo=FALSE)

#color scheme
ciri_colors <- c('#fe7241', '#ae5944', '#543c4a', '#67444a')
```

For overall model: RMSEA <= .06 and SRMSR <= .08 suggest good fit. 

For individual items: RMSEA < .06 suggest adequate fit.


```{r}
mirt_fit <- function(variable_list){
  #variable_list <- Entrskills_vars
  
  df <- T0_constructs_df[variable_list]

  # fit IRT model
  mod <- (mirt(df, 1, verbose = FALSE, itemtype = 'graded', SE = TRUE))

  # model fit for response models with ordinal data
  print(M2(mod, type = "C2", calcNULL = FALSE, na.rm=TRUE))
  
  return(mod)
}
```

```{r}
loc <- mirt_fit(LoC_vars)

plot(loc, type = 'trace', theta_lim = c(-3, 3))
plot(loc, type = 'infotrace', theta_lim = c(-3, 3))
plot(loc, type = 'infoSE', theta_lim = c(-3, 3))
```
```{r}
entr <- mirt_fit(Entrskills_vars)

plot(entr, type = 'trace', theta_lim = c(-3, 3))
plot(entr, type = 'infotrace', theta_lim = c(-3, 3))
plot(entr, type = 'infoSE', theta_lim = c(-3, 3))
```
```{r}
nfa <- mirt_fit(NFA_vars)

plot(nfa, type = 'trace', theta_lim = c(-3, 3))
plot(nfa, type = 'infotrace', theta_lim = c(-3, 3))
plot(nfa, type = 'infoSE', theta_lim = c(-3, 3))
```
```{r}
T0_constructs_df[NFA_vars] |>
  pivot_longer(cols = c("NfA_0001", "NfA_0002", "NfA_0003", "NfA_0004"), values_to = "variable") |>
  ggplot(aes(x=name, y=variable)) +
    ggdist::stat_halfeye(
      show.legend = FALSE, 
      #adjust = 1,  # the breaks / bins of histogram
      width = .5, 
      justification = -.2,
      #.width = c(.5, .95)
      ) +
    scale_fill_manual(values=ciri_colors) +
    geom_boxplot(
      show.legend = FALSE,
      width = .12, 
      coef = 0, 
      outlier.color = NA
    )  +
    gghalves::geom_half_point(
      transformation =  position_jitter(height = .2),
      show.legend = FALSE, 
      side="1", 
      range_scale=.2,
      alpha = .45
      ) +
  theme_minimal() +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  ylim("1", "2", "3", "4", "5")
```


```{r}
tfa <- mirt_fit(TfA_vars)

plot(tfa, type = 'trace', theta_lim = c(-3, 3))
plot(tfa, type = 'infotrace', theta_lim = c(-3, 3))
plot(tfa, type = 'infoSE', theta_lim = c(-3, 3))
```

